### ISSUE TITLE
Non idempotence due to management of groups in the design

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/jujubigdata#39]
flume-kafka charm not managing the existence of groups prior to deployment. Essentially, if you collocate 2 charms of the big data group, you'll end with the below log & error. 
It  seems to be a pattern in all big data charms, don't know if this is fixed in the layered versions, but for these, it would make sense in the management of groups and users to add a test like "if exist OK, otherwise create / modify / foobar". 

```
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.juju-log server.go:268 zookeeper:9: group hadoop already exists!
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40 Traceback (most recent call last):
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-kafka-broker-0/charm/hooks/zookeeper-relation-changed", line 15, in <module>
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     common.manage()
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-kafka-broker-0/charm/hooks/common.py", line 86, in manage
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     manager.manage()
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/usr/local/lib/python2.7/dist-packages/charmhelpers/core/charmframework/base.py", line 115, in manage
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     self.run_callbacks()
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/usr/local/lib/python2.7/dist-packages/charmhelpers/core/charmframework/base.py", line 159, in run_callbacks
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     self.fire_event('callbacks', component)
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/usr/local/lib/python2.7/dist-packages/charmhelpers/core/charmframework/base.py", line 189, in fire_event
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     callback()
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-kafka-broker-0/charm/hooks/callbacks.py", line 58, in install
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     self.dist_config.add_users()
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40   File "/usr/local/lib/python2.7/dist-packages/jujubigdata/utils.py", line 141, in add_users
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40     host.adduser(username, group=primary_group)
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 INFO unit.kafka-broker/0.zookeeper-relation-changed logger.go:40 TypeError: adduser() got an unexpected keyword argument 'group'
unit-kafka-broker-0[5695]: 2016-02-05 10:52:42 ERROR juju.worker.uniter.operation runhook.go:107 hook "zookeeper-relation-changed" failed: exit status 1

```

**Comment by kwmonroe** [comment]
Hi Sam - I'm sorry you hit this problem.  FYI, a pre-existing 'hadoop' group is not the real issue -- we happily skip over existing groups and just log that info.  The real culprit is:

TypeError: adduser() got an unexpected keyword argument 'group'

This occurred because of a signature change to the adduser() method in the jujubigdata library.  I suspect your apache-flume-kafka charm came from the ~bigdata-dev namespace (which uses v5) and your apache-flume came from the recommended namespace (which uses v4).  Mixing dev and production charms won't always work when there's a different major version of the jujubigdata library (major versions signify API incompatibility in this library).

The solution is for us to get apache-flume-kafka promulgated, or have you switch to all ~bigdata-dev charms.  Again, I'm sorry for the inconvenience this caused, but we have no plans to support mixing dev and prod charms in the same deployment.

**Comment by SaMnCo** [comment]
Whaow good catch, I didn't realize I was doing that. I'll check again
tomorrow. Thanks for having a look.

++
Sam
